--- #YAML:1.0
name:                Text-SimpleVcard
version:             0.05
abstract:            a package to manage a single vCard
license:             ~
author:              
    - Michael Tomuschat <tomuschat@perl.org>
generated_by:        ExtUtils::MakeMaker version 6.42
distribution_type:   module
requires:     
    Test::More:                    0
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.3.html
    version: 1.3
